version: '3.1'
services:
  mysql:
   image: mysql
   container_name: vest-db-test-home
   ports:
    - 3307:3306
   environment:
     MYSQL_DATABASE: path
     MYSQL_ROOT_PASSWORD: 123456ABC
   volumes:
    - ./dump:/docker-entrypoint-initdb.d